<?xml version="1.0" encoding="UTF-8"?>
<testsuite hostname="MININT-3U4P43Q" name="org.jlayer.app.MatrixTest" tests="1" failures="0" timestamp="17 Oct 2016 17:09:49 GMT" time="0.036" errors="0">
  <testcase name="@BeforeClass beforeClass" time="0.0" classname="org.jlayer.app.MatrixTest">
    <failure type="java.lang.AbstractMethodError">
      <![CDATA[java.lang.AbstractMethodError
	at org.testng.internal.Invoker.runConfigurationListeners(Invoker.java:1805)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:204)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:132)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:173)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1182)
	at org.testng.TestRunner.privateRun(TestRunner.java:761)
	at org.testng.TestRunner.run(TestRunner.java:612)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:241)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1169)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1094)
	at org.testng.TestNG.run(TestNG.java:1006)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase>
  <testcase name="test2" time="0.008" classname="org.jlayer.app.MatrixTest">
    <skipped/>
  </testcase>
</testsuite>
